services:
  postgres:
    restart: always
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    networks:
      dockonekt-referral:

  directus:
    restart: always
    image: directus/directus:11.3.2
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8058:8058"
    env_file:
      - .env
    extra_hosts:
      - "dockonekt.hustlerati.com:host-gateway"
    environment:                                                                                                                                                                
      DB_TYPE: postgres  # Specify the database type
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres  # Use the service name as the host
      DB_PORT: 5432   
      EXTENSIONS_AUTO_RELOAD: true
    networks:
      dockonekt-referral:
    volumes:
      - ./docker/directus/uploads:/directus/uploads
      - ./docker/directus/extensions:/directus/extensions
      - ./docker/directus/database:/directus/database
      - ./docker/directus/templates:/directus/templates

  express:
    restart: always
    build: .
    depends_on: 
      - directus
      - redis
    env_file:
      - .env
    environment:
      PORT: ${EXPRESS_PORT}
      SALT_ROUNDS: 10
      DIRECTUS_URL: "http://directus:8058"
      DIRECTUS_TOKEN: ${DIRECTUS_TOKEN}
      REDIS_URL: "redis://redis:6379"
    networks:
      dockonekt-referral:
    ports:
      - "127.0.0.1:4000:4000"

  redis:
    restart: always
    image: redis:7.0.11
    ports:
      - "6379:6379"
    networks:
      dockonekt-referral:

networks:
  dockonekt-referral:                                                                                
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.70.0/24 